CREATE TABLE IF NOT EXISTS courseGroup (
  id INTEGER PRIMARY KEY,
  guildId INTEGER NOT NULL,
  name TEXT NOT NULL,
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (guildId, name)
);

CREATE TABLE IF NOT EXISTS course (
  id INTEGER PRIMARY KEY,
  courseGroupId INTEGER NOT NULL,
  name TEXT NOT NULL,
  channelId INTEGER UNIQUE,
  ord INTEGER,
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (courseGroupId, name)
);

CREATE TABLE IF NOT EXISTS module (
  id INTEGER PRIMARY KEY,
  courseGroupId INTEGER NOT NULL,
  courseId INTEGER NOT NULL,
  name TEXT NOT NULL,
  ord INTEGER,
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (courseId, name),
  FOREIGN KEY (courseGroupId) REFERENCES courseGroup(id) ON DELETE CASCADE,
  FOREIGN KEY (courseId) REFERENCES course(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS checkEntry (
  id INTEGER PRIMARY KEY,
  userId INTEGER,
  moduleId INTEGER NOT NULL,
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (userId, moduleId),
  FOREIGN KEY (moduleId) REFERENCES module(id) ON DELETE CASCADE
);
